be15-fin-tomato/be15-fin-tomato-katchup-FE

- src/features/campaign/components/CampaignForm.vue
- src/mocks/api/handler/CampaignHandler.js
[fix: 파이프라인 상품 정보 추가](http://localhost:5173/campaign/1)
> fix: 파이프라인 상품 정보 추가

- src/App.vue
- src/assets/styles/tailwind.css
- src/components/layout/OpinionBar.vue
- src/components/layout/SearchPopup.vue
- src/features/campaign/api.js
- src/features/campaign/components/DetailReferenceList.vue
- src/features/campaign/components/QuotationForm.vue
- src/features/campaign/router.js
- src/features/campaign/views/QuotationDetail.vue
- src/features/campaign/views/SearchPopup.vue
- src/mocks/api/handler/CampaignHandler.js
http://localhost:5173/quotation/1
> Tmt 30 fe 견적 상세 정보 페이지 개발

- src/features/user/views/findPasswordView.vue
> [FE] 비밀번호 찾기 페이지 구현

- package-lock.json
- src/features/influencer/components/chart/AlgorithmChart.vue
- src/features/influencer/components/chart/GenderChart.vue
- src/features/influencer/components/chart/ReachChart.vue
- src/features/influencer/views/CampaginResultDashboardView.vue
최대 100점
소수점 아래가 0이면 소수점 안 보이게 수정
호버하면 계산식 조회 가능
> fix: 알고리즘스코어, 활성도, 참여도 수치 조회 기능 추가

- src/features/mypage/views/MyPageView.vue
- 프로필 사진 변경
- 프로필 클릭 시 해당 인플루언서 id에 유튜브 대시보드로 이동
http://localhost:5173/mypage
> Fix: 프로필 클릭 시 라우터 이동

- src/features/calendar/components/Calendar.vue
> Fix: 캘린더 클릭 시 색상 변경

- package-lock.json
- package.json
- src/features/user/components/ChartCard.vue
- src/features/user/components/DoughnutChart.vue
- src/features/user/components/SatisfactionCard.vue
- src/features/user/router.js
- src/features/user/views/SurveyListView.vue
- src/mocks/api/browser.js
- src/mocks/api/handler/SatisfactionHandler.js
> [FE] 만족도 조사 목록 페이지 구현

- src/features/chat/components/ChatRoom.vue
> refactor: 채팅 첨부파일 수정

- package-lock.json
- src/features/dashboard/components/AnalyticsFilters.vue
- src/features/dashboard/components/GoogleSearchData.vue
- src/features/dashboard/components/NaverSearchData.vue
- src/features/dashboard/components/chart/RevenueSummary.vue
- src/features/dashboard/components/chart/TrafficSourcesChart.vue
> fix: 성과 대시보드 타이틀 추가

- src/features/user/components/ChartCard.vue
- src/features/user/components/DoughnutChart.vue
- src/features/user/components/SatisfactionCard.vue
> [FE] 만족도 조사 페이지 수정

- src/components/common/UserPanel.vue
- src/components/layout/Header.vue
- 상위 메뉴 클릭하면 첫번째 하위 메뉴로 이동
- 영업관리 + 파이프라인 합친 후 캠페인으로 상위 메뉴 이름 변경 (헷갈려서 url은 그대로 놔뒀어요)
- 인플루언서 목록 → 대시보드 (이름 변경)
- 관리 → 고객사 (이름 변경)
카테고리가 좀 비어 보이는데 이건 나중에 한 번 더 상의한 뒤에 수정하구,, 안 거슬리면 그냥 놔두시죠!!
> Tmt 87 fe 헤더 카테고리 수정

- src/features/contract/components/SmallTemplateEditModal.vue
- src/features/contract/components/SmallTemplateModal.vue
- src/features/contract/views/ContractTemplateView.vue
> refactor: 템플릿 이름 변경

- src/features/user/components/EmailCard.vue
- src/features/user/components/SatisfactionScoreModal.vue
> feat: 만족도 항목별 점수 조회

- src/features/contract/views/ContractListView.vue
> Fix: 계약 완료 목록 수정

- package-lock.json
- package.json
- src/features/dashboard/components/chart/RevenueSummary.vue
- src/features/dashboard/components/chart/TrafficSourcesChart.vue
- src/features/dashboard/components/chart/WordCloud.vue
- src/main.js
- src/plugin/axios.js
> refactor: 성과 대시보드 페이지 수정

- src/features/user/components/InfluencerFormModal.vue
> refactor: 인플루언서 등록 페이지 수정

- src/components/common/UserPanel.vue
- src/features/user/api.js
- src/features/user/views/LoginView.vue
- src/main.js
- src/plugin/axios.js
- src/router/index.js
- src/stores/auth.js
> chore: 로그인, 로그아웃 연동

- src/components/common/SearchPopup.vue
- src/components/layout/OpinionBar.vue
- src/features/campaign/api.js
- src/features/campaign/components/DetailReferenceList.vue
- src/features/campaign/components/SalesCards.vue
- src/features/campaign/components/SalesForm.vue
- src/features/campaign/utils/structedForm.js
- src/features/campaign/views/ProposalDetail.vue
- src/features/campaign/views/ProposalList.vue
- src/features/campaign/views/QuotationDetail.vue
- src/features/campaign/views/QuotationList.vue
- src/features/contract/components/SendEmail.vue
- 견적 목록 초기 조회 연동
- 견적 상세 페이지 초기 조회 연동
- 팝업 검색 연동
> [연동] 견적 연동

- src/components/common/UserPanel.vue
- src/features/mypage/api.js
- src/features/mypage/components/ExchangePassword.vue
- src/features/mypage/views/MyPageView.vue
- src/features/user/api.js
- src/features/user/views/LoginView.vue
- src/features/user/views/findPasswordView.vue
> Tmt 209 fe 회원 및 마이페이지 연동 구현

- package-lock.json
- package.json
- public/firebase-messaging-sw.js
- src/App.vue
- src/components/common/UserPanel.vue
- src/features/user/api.js
- src/features/user/views/LoginView.vue
- src/utils/token.js
알림 연동했습니다~
혹시 콘솔에서 sse 연결실패뜨면 재로그인하면 됩니다.. (저도 왜그런진 몰라요 가끔씩 이래서 나중에 수정해볼게요)
> Tmt 210 fe 알림 연동 구현

- src/components/common/PagingBar.vue
- src/features/advertisement/api.js
- src/features/advertisement/components/ClientFiltering.vue
- src/features/advertisement/views/ClientListView.vue
> Tmt 122 fe 고객사 검색 필터링 사이드바 구현 및 연동

- package-lock.json
- src/components/common/InfluencerCard.vue
- src/constants/tags.js
- src/features/influencer/api.js
- src/features/influencer/components/InfluencerCategory.vue
- src/features/influencer/views/InfluencerListView.vue
인플루언서 목록 조회 기능 구현
- 추후에 인스타그램, 유튜브 연동 관련 기능 추가 예정 
- 지금은 목록 조회만,,
> Tmt 218 fe 인플루언서 목록 조회 대시보드

- src/features/advertisement/api.js
- src/features/advertisement/components/ClientCreateForm.vue
- src/features/advertisement/views/ClientCreateView.vue
- 등록 폼 저장 버튼 하나로 고객사와 사원 정보 한 번에 저장할 수 있도록 UI/UX 수정
- 고객사 등록 API 연동 완료
> Tmt 125 fe 고객사 및 사원 저장 수정 페이지 로직 변경 및 연동

- src/components/common/InfluencerManagementCard.vue
- src/features/user/api.js
- src/features/user/views/InfluencerManagementView.vue
> Tmt 237 연동 인플루언서 관리 연동

- src/components/common/InfluencerCard.vue
- src/features/influencer/api.js
- src/features/influencer/views/InfluencerListView.vue
인플루언서 대시보드쪽 목록 조회 실제 테이블에 있는 데이터로 연결
아직 대시보드쪽은 안 돼서 대시보드쪽으로는 안 넘어가져요 (인플루언서 id는 넘겨주게 만들어 놓음)
> Tmt 233 fe 인플루언서 채널 정보 api 연동

- src/App.vue
- src/features/main/views/Main.vue
- src/features/user/views/InfluencerManagementView.vue
1. 페이지에 채팅 버튼 띄우기
2. 아이콘 수정
3. 인스타 팔로워 표시 수정
> Tmt 241 채팅 모든페이지에 띄우기

- src/features/chat/components/ChatListModal.vue
호버와 디자인 변경
채팅방 제목이 길어졌을 때 요약 기능 구현
> Tmt 251 연동 채팅 세부사항 수정

- package-lock.json
- src/features/advertisement/api.js
- src/features/advertisement/components/ClientCard.vue
- src/features/advertisement/components/ClientCompanyForm.vue
- src/features/advertisement/router.js
- src/features/advertisement/views/ClientCreateView.vue
- src/features/advertisement/views/ClientDetailView.vue
고객사, 사원 상세 정보 조회 연동
고객사, 사원 정보 수정 연동
> Tmt 228 fe 고객사와 사원 정보 조회 및 수정 연동

- src/features/campaign/components/SalesCards.vue
- src/features/contract/components/SendEmail.vue
- src/features/dashboard/api.js
- src/features/dashboard/components/CampaignResultCard.vue
- src/features/dashboard/views/CampaignResultListView.vue
- src/features/user/views/InfluencerManagementView.vue
1. 조회 구현 완료
2. 다음 브랜치에서 필터링이랑 댓글요약 , 키워드 검색 비율 하겠습니다
> Tmt 255 연동 캠페인 성과 목록 연동

- src/features/advertisement/api.js
- src/features/advertisement/components/ClientCompanyForm.vue
- src/features/advertisement/views/ClientDetailView.vue
- 고객사 전체 삭제 연동
- 삭제 로직 재구성
- 고객사의 사원 단독 삭제 연동
> Tmt 231 fe 고객사 삭제 UI 구현 및 연동

- src/App.vue
- src/components/common/SearchPopup.vue
- src/components/layout/CommonFiltering.vue
- src/components/layout/SalesFiltering.vue
- src/features/campaign/components/DetailReferenceList.vue
- src/features/campaign/components/SalesForm.vue
- src/features/campaign/utils/validator.js
- src/features/campaign/views/ContractCreate.vue
- src/features/campaign/views/ContractDetail.vue
- src/features/campaign/views/ProposalCreate.vue
- src/features/campaign/views/ProposalDetail.vue
- src/features/campaign/views/QuotationCreate.vue
- src/features/campaign/views/QuotationDetail.vue
- src/features/campaign/views/RevenueCreate.vue
- src/features/campaign/views/RevenueDetail.vue
- src/features/user/components/Filtering.vue
파이프라인 에러 처리 수정
- 필수 입력 값 * 표시
- 필수 입력 값 미입력시 에러 메시지 출력
- 사이드바 필터/정렬 분리
> 파이프라인 에러 처리 수정

- src/components/common/InfluencerManagementFilter.vue
- src/components/layout/CommonFiltering.vue
- src/features/contract/components/SendEmail.vue
- src/features/user/api.js
- src/features/user/views/InfluencerManagementView.vue
> Tmt 260 연동 전체적인 수정

- src/components/common/InfluencerManagementFilter.vue
- src/features/user/api.js
- src/features/user/views/InfluencerManagementView.vue
> feat: 카테고리 추가

- src/components/common/InfluencerCard.vue
- src/features/influencer/views/InfluencerListView.vue
> Tmt 271 fe 인플루언서 대시보드 목록 로딩 처리

- src/features/dashboard/api.js
- src/features/dashboard/components/CampaignHeaderCard.vue
- src/features/dashboard/components/GoogleSearchData.vue
- src/features/dashboard/components/NaverSearchData.vue
- src/features/dashboard/components/chart/CampaignVideoSummary.vue
- src/features/dashboard/components/chart/TrafficSourcesChart.vue
- src/features/dashboard/components/chart/YoutubeAnalyticsChart.vue
- src/features/dashboard/views/CampaignResultDashboardView.vue
- src/features/dashboard/views/CampaignResultListView.vue
> Tmt 276 연동 성과 대시보드

- src/features/dashboard/api.js
- src/features/dashboard/components/CampaignHeaderCard.vue
- src/features/dashboard/components/NaverSearchData.vue
- src/features/dashboard/components/chart/CampaignVideoSummary.vue
- src/features/dashboard/views/CampaignResultDashboardView.vue
> Tmt 285 연동 컨텐츠 정보조회 연동

- src/components/common/InfluencerListFilter.vue
- src/components/common/InfluencerManagementFilter.vue
- src/features/influencer/components/InfluencerCategory.vue
- src/features/influencer/views/InfluencerListView.vue
- src/plugin/axios.js
대시보드 - 인플루언서 분석 페이지 사이드바 수정 (가격 항목 삭제)
> Tmt 292 fe 인플루언서 분석 사이드바 수정

- src/features/campaign/utils/structedForm.js
> 파이프라인 인플루언서 이름 안보이는 오류 수정

- src/features/chat/components/ChatListModal.vue
- src/features/chat/components/ChatRoom.vue
- src/features/contract/views/ContractTemplateView.vue
- src/features/dashboard/views/CampaignResultListView.vue
> refactor: 알림 toast 교체

- src/components/common/InfluencerListFilter.vue
> 인플루언서 분석 페이지 사이드바 수정

- src/components/common/InfluencerCard.vue
- src/components/common/InfluencerListFilter.vue
- src/features/dashboard/components/CampaignHeaderCard.vue
- src/features/influencer/views/InfluencerListView.vue
> 사이드바 초기화 기능 수정

- src/features/ai/api.js
- src/features/ai/views/AIRecommendView.vue
- src/features/influencer/components/InfluencerFormModal.vue
> 인플루언서 등록/수정 화면 이메일 삭제

- src/features/influencer/components/InfluencerCardSkeleton.vue
- src/features/influencer/views/InfluencerListView.vue
> fix: 인플루언서 목록 페이지 스켈레톤 추가

- src/features/influencer/views/InfluencerManagementView.vue
- src/features/main/components/SalesDashboard.vue
- src/features/main/views/Main.vue
> Tmt 307 fe 메인 대시보드 라우팅 수정

- src/components/common/InfluencerCard.vue
- src/features/influencer/components/InfluencerCategory.vue
- src/features/influencer/views/InfluencerListView.vue
> Tmt 314 fe 인플루언서 대시보드 목록 수정

- src/features/calendar/router.js
- src/features/calendar/views/CalendarView.vue
- src/features/campaign/views/SalesDetailRouter.vue
캠페인 파이프라인 일정과 해당 캠페인 상세 페이지 연결
> fix - 파이프라인 일정과 해당 캠페인 상세 페이지 연결

- src/features/chat/components/ChatRoom.vue
- src/features/contract/views/ContractListView.vue
- src/features/dashboard/api.js
- src/features/dashboard/components/AnalyticsFilters.vue
- src/features/dashboard/components/CampaignHeaderCard.vue
- src/features/dashboard/components/chart/RevenueSummary.vue
- src/features/dashboard/components/chart/TrafficSourcesChart.vue
- src/features/dashboard/components/chart/YoutubeAnalyticsChart.vue
- src/features/dashboard/views/CampaignResultDashboardView.vue
- src/features/dashboard/views/CampaignResultListView.vue
> refactor : 전체적인 수정

- src/assets/styles/tailwind.css
- src/components/common/SearchPopup.vue
- src/components/layout/OpinionBar.vue
- src/components/layout/SalesFiltering.vue
- src/features/ai/components/AIInfluencerCard.vue
- src/features/ai/components/AddToListupModal.vue
- src/features/ai/components/AddedInfluencers.vue
- src/features/ai/views/AIRecommendView.vue
- src/features/campaign/components/ProposalAccordionItem.vue
- src/features/campaign/components/SalesCards.vue
- src/features/campaign/views/ContractCreate.vue
- src/features/campaign/views/ContractDetail.vue
- src/features/campaign/views/ContractList.vue
- src/features/campaign/views/ListUpList.vue
- src/features/campaign/views/ProposalCreate.vue
- src/features/campaign/views/ProposalDetail.vue
- src/features/campaign/views/ProposalList.vue
- src/features/campaign/views/QuotationCreate.vue
- src/features/campaign/views/QuotationDetail.vue
- src/features/campaign/views/QuotationList.vue
- src/features/campaign/views/RevenueCreate.vue
- src/features/campaign/views/RevenueDetail.vue
- src/features/campaign/views/RevenueList.vue
- src/main.js
- src/stores/auth.js
> 파이프라인 오류 수정

- src/components/layout/HorizontalFiltering.vue
- src/features/campaign/components/PipelineDiagram.vue
- src/features/contract/components/ContractUploadModal.vue
- src/features/contract/views/ContractListView.vue
> Fix: 캠페인 목록 체크된 단계까지 나오게 변경

- src/features/dashboard/components/chart/TrafficSourcesChart.vue
- src/features/user/api.js
- src/features/user/components/EmailCard.vue
> fix: 알림 배포로 수정

- src/features/chat/components/ChatListModal.vue
- src/features/chat/components/ChatRoom.vue
> refactor : 채팅 수정

- src/App.vue
> refactor : 채팅 실시간 반영

- src/App.vue
- src/features/chat/components/ChatRoom.vue
> refactor : 외부 클릭
